/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zuehlke.carrera.ressource.thrift;


import org.apache.thrift.TEnum;

public enum RaceTypeThrift implements TEnum {
  TRAINING(0),
  COMPETITION(1);

  private final int value;

  private RaceTypeThrift(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RaceTypeThrift findByValue(int value) { 
    switch (value) {
      case 0:
        return TRAINING;
      case 1:
        return COMPETITION;
      default:
        return null;
    }
  }
}
